### ISSUE TITLE
 搜索出现图片，没有定义图片大小，导致图片很大

### ISSUE THREAD

**Issue by chengzhongxue** [halo-dev/plugin-search-widget#21]
![image](https://github.com/halo-dev/plugin-search-widget/assets/89380218/3d4fcf86-e166-432d-af6c-9d7512438066)

**Comment by ruibaby** [comment]
@JohnNiang 出现图片是符合预期的吗？

**Comment by JohnNiang** [comment]
Hi @ruibaby ，建议在搜索组件中修改样式来适配。

/kind bug
