### ISSUE TITLE
可否开放或者增加搜索提示的英文版

### ISSUE THREAD

**Issue by lunapapa-finland** [halo-dev/plugin-search-widget#30]
可否开放或者增加搜索提示的英文版？ 这个其实也包括了评论插件。这两个插件目前无法通过前端修改中文为英文，请酌情考虑。目前在改一个英文版的主题，发现插件设计到的语言都没办法修改。

**Comment by lunapapa-finland** [comment]
请问这个有人回复么？

**Comment by ruibaby** [comment]
当前暂无计划提供多语言，如果你只是想修改语言之后自行使用，建议 fork 这个仓库，然后替换文本。构建和开发文档：https://github.com/halo-dev/plugin-search-widget#%E5%BC%80%E5%8F%91%E7%8E%AF%E5%A2%83
