### ISSUE TITLE
关键词为空的情况下无法正常渲染页面

### ISSUE THREAD

**Issue by chengzhongxue** [halo-dev/plugin-search-widget#37]
![1720024463380](https://github.com/halo-dev/plugin-search-widget/assets/89380218/a8a9ba79-4d01-4e9b-9a45-7fa421995574)
如果搜索的内容条数超出设置的limit值，怎么查看下一页的内容呢，
是不是没有下一页参数

**Comment by chengzhongxue** [comment]
http://localhost:8099/search?keyword=   
keyword内容为空页面就会 
![image](https://github.com/halo-dev/plugin-search-widget/assets/89380218/2594ad2a-4b34-465e-b63d-f231975e3e2a)
是不是要做一下处理

**Comment by ruibaby** [comment]
> ![1720024463380](https://private-user-images.githubusercontent.com/89380218/345526479-a8a9ba79-4d01-4e9b-9a45-7fa421995574.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNzY1NjYsIm5iZiI6MTcyMDA3NjI2NiwicGF0aCI6Ii84OTM4MDIxOC8zNDU1MjY0NzktYThhOWJhNzktNGQwMS00ZTliLTlhNDUtN2ZhNDIxOTk1NTc0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDA2NTc0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3NjlkMWU0MDNlMDU4Y2YxYWVjNGFiMDU1NDEzMTVlMTQyNGQzOTU3MmFjY2Q4MjA3ZjI3YzMzNDFjOGI3YTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s6oCWyhwdPrUR97pYXEHfg7CSBNQWOw06U3U72zzcuE) 如果搜索的内容条数超出设置的limit值，怎么查看下一页的内容呢， 是不是没有下一页参数

暂时不支持分页

**Comment by chengzhongxue** [comment]
> > ![1720024463380](https://private-user-images.githubusercontent.com/89380218/345526479-a8a9ba79-4d01-4e9b-9a45-7fa421995574.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNzY1NjYsIm5iZiI6MTcyMDA3NjI2NiwicGF0aCI6Ii84OTM4MDIxOC8zNDU1MjY0NzktYThhOWJhNzktNGQwMS00ZTliLTlhNDUtN2ZhNDIxOTk1NTc0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDA2NTc0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3NjlkMWU0MDNlMDU4Y2YxYWVjNGFiMDU1NDEzMTVlMTQyNGQzOTU3MmFjY2Q4MjA3ZjI3YzMzNDFjOGI3YTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s6oCWyhwdPrUR97pYXEHfg7CSBNQWOw06U3U72zzcuE) 如果搜索的内容条数超出设置的limit值，怎么查看下一页的内容呢， 是不是没有下一页参数
> 
> 暂时不支持分页

这个需要分页？还是说有更好的办法

**Comment by JohnNiang** [comment]
Hi @chengzhongxue ，暂时没有计划分页，后续根据更多的反馈来决定是否需要提供 offset 的参数。

**Comment by chengzhongxue** [comment]
> Hi @chengzhongxue ，暂时没有计划分页，后续根据更多的反馈来决定是否需要提供 offset 的参数。

好的
