### ISSUE TITLE
1.6.2版本搜不到文章

### ISSUE THREAD

**Issue by Mr-Zhan005** [halo-dev/plugin-search-widget#48]
Halo 2.17.2版本
主题：joe3 1.2.2

之前的搜索组件能搜到，更新了2.17版本，测试了1.6、1.5和1.4版本搜索组件，以前的文章搜不到，只搜到首页上的一些新文章

**Comment by ruibaby** [comment]
先尝试在仪表盘刷新搜索引擎索引。

**Comment by verkyer** [comment]
1.6.2 文章搜索 对于英文单词，都需要输入完整的才会显示的吗？
比如一些比较长的，或难以记住的完全搜索不到
![Image](https://github.com/user-attachments/assets/4e6b2d3b-c38b-4543-af5e-20eb44e69743)
![Image](https://github.com/user-attachments/assets/a0533c6a-052b-42cf-b49e-20ebb74eac89)

**Comment by ruibaby** [comment]
搜索匹配度问题与此插件无关，此插件仅提供 UI 组件和页面，和搜索相关的问题建议在 https://github.com/halo-dev/halo 提交，相关问题：https://github.com/halo-dev/halo/issues/6328

此外，如果对内置的搜索引擎的搜索结果不满意，建议自建 Meilisearch 搜索引擎，Halo 社区有集成 Meilisearch 的插件：https://www.halo.run/store/apps/app-DlacW

/close
